// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRepository(arg1) {
  return window['go']['main']['App']['CreateRepository'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTaskWithJiraTitle(arg1) {
  return window['go']['main']['App']['CreateTaskWithJiraTitle'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteRepository(arg1) {
  return window['go']['main']['App']['DeleteRepository'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function FetchJiraTicketTitle(arg1) {
  return window['go']['main']['App']['FetchJiraTicketTitle'](arg1);
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetKubernetesResourceActions(arg1, arg2) {
  return window['go']['main']['App']['GetKubernetesResourceActions'](arg1, arg2);
}

export function GetKubernetesResources(arg1) {
  return window['go']['main']['App']['GetKubernetesResources'](arg1);
}

export function GetMicroserviceActions(arg1, arg2) {
  return window['go']['main']['App']['GetMicroserviceActions'](arg1, arg2);
}

export function GetMicroservices(arg1) {
  return window['go']['main']['App']['GetMicroservices'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRecentActions(arg1, arg2) {
  return window['go']['main']['App']['GetRecentActions'](arg1, arg2);
}

export function GetRepositories() {
  return window['go']['main']['App']['GetRepositories']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetTasksByProject(arg1) {
  return window['go']['main']['App']['GetTasksByProject'](arg1);
}

export function GetTasksGroupedByScheduledDate() {
  return window['go']['main']['App']['GetTasksGroupedByScheduledDate']();
}

export function GetTasksInDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetTasksInDateRange'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RefreshAllJiraTitles() {
  return window['go']['main']['App']['RefreshAllJiraTitles']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SyncRepository(arg1) {
  return window['go']['main']['App']['SyncRepository'](arg1);
}

export function TestJiraConnection() {
  return window['go']['main']['App']['TestJiraConnection']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateRepository(arg1) {
  return window['go']['main']['App']['UpdateRepository'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpdateTaskJiraTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskJiraTitle'](arg1, arg2);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
